// <auto-generated />
namespace PatioBlox2016.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ConvertKeywordToHierarchy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ConvertKeywordToHierarchy));
        
        string IMigrationMetadata.Id
        {
            get { return "201509061405421_ConvertKeywordToHierarchy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
