//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatioBlox.Domain.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\SAN\\AraxiVolume_InSiteJobs\\Jobs\\Lowes US 2014 Patio Blocks\\UserDefinedFolders\\P" +
            "atchAreas\\factory")]
        public string FactoryRootPath {
            get {
                return ((string)(this["FactoryRootPath"]));
            }
            set {
                this["FactoryRootPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("support")]
        public string SubpathSupport {
            get {
                return ((string)(this["SubpathSupport"]));
            }
            set {
                this["SubpathSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data")]
        public string SubpathData {
            get {
                return ((string)(this["SubpathData"]));
            }
            set {
                this["SubpathData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("report")]
        public string SubPathReport {
            get {
                return ((string)(this["SubPathReport"]));
            }
            set {
                this["SubPathReport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jsx")]
        public string SubpathJsx {
            get {
                return ((string)(this["SubpathJsx"]));
            }
            set {
                this["SubpathJsx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("template\\slot")]
        public string SubPathTemplateSlot {
            get {
                return ((string)(this["SubPathTemplateSlot"]));
            }
            set {
                this["SubPathTemplateSlot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("template\\composite")]
        public string SubPathTemplateComposite {
            get {
                return ((string)(this["SubPathTemplateComposite"]));
            }
            set {
                this["SubPathTemplateComposite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("output\\slot\\indd")]
        public string SubPathOutputSlotIndd {
            get {
                return ((string)(this["SubPathOutputSlotIndd"]));
            }
            set {
                this["SubPathOutputSlotIndd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("output\\slot\\pdf")]
        public string SubPathOutputSlotPdf {
            get {
                return ((string)(this["SubPathOutputSlotPdf"]));
            }
            set {
                this["SubPathOutputSlotPdf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("output\\composite\\indd")]
        public string SubPathOutputCompositeIndd {
            get {
                return ((string)(this["SubPathOutputCompositeIndd"]));
            }
            set {
                this["SubPathOutputCompositeIndd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("output\\composite\\pdf")]
        public string SubPathOutputCompositePdf {
            get {
                return ((string)(this["SubPathOutputCompositePdf"]));
            }
            set {
                this["SubPathOutputCompositePdf"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JobFolders.jsx")]
        public string JobFoldersFileName {
            get {
                return ((string)(this["JobFoldersFileName"]));
            }
            set {
                this["JobFoldersFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ProductData.jsx")]
        public string ProductDataFileName {
            get {
                return ((string)(this["ProductDataFileName"]));
            }
            set {
                this["ProductDataFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PatchData.jsx")]
        public string PatchDataFileName {
            get {
                return ((string)(this["PatchDataFileName"]));
            }
            set {
                this["PatchDataFileName"] = value;
            }
        }
    }
}
